name: ci-cd
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o codigo do projeto
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD  }}
        
      - name: Construção da imagem docker e push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            joaolopesneto/fake-shop:latest
            joaolopesneto/fake-shop:v${{ github.run_number }}
      
  cd:
    runs-on: ubuntu-latest
    needs: ["ci"]
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando aws configure"
      - name: Configurar o Kubectl
        run: echo "Executando o comando aws eks update kubconfig"
      - name: Deploy manifestos kubernets
        run: echo "Executando o comando kubectl apply"
